// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: tweets/tweets.proto

package tweets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRequest) Reset() {
	*x = FlushRequest{}
	mi := &file_tweets_tweets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRequest) ProtoMessage() {}

func (x *FlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tweets_tweets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRequest.ProtoReflect.Descriptor instead.
func (*FlushRequest) Descriptor() ([]byte, []int) {
	return file_tweets_tweets_proto_rawDescGZIP(), []int{0}
}

type FlushReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushReply) Reset() {
	*x = FlushReply{}
	mi := &file_tweets_tweets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushReply) ProtoMessage() {}

func (x *FlushReply) ProtoReflect() protoreflect.Message {
	mi := &file_tweets_tweets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushReply.ProtoReflect.Descriptor instead.
func (*FlushReply) Descriptor() ([]byte, []int) {
	return file_tweets_tweets_proto_rawDescGZIP(), []int{1}
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Sync          bool                   `protobuf:"varint,3,opt,name=sync,proto3" json:"sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_tweets_tweets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tweets_tweets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_tweets_tweets_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetSync() bool {
	if x != nil {
		return x.Sync
	}
	return false
}

type PutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutReply) Reset() {
	*x = PutReply{}
	mi := &file_tweets_tweets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutReply) ProtoMessage() {}

func (x *PutReply) ProtoReflect() protoreflect.Message {
	mi := &file_tweets_tweets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutReply.ProtoReflect.Descriptor instead.
func (*PutReply) Descriptor() ([]byte, []int) {
	return file_tweets_tweets_proto_rawDescGZIP(), []int{3}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_tweets_tweets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tweets_tweets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_tweets_tweets_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_tweets_tweets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_tweets_tweets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_tweets_tweets_proto_rawDescGZIP(), []int{5}
}

func (x *GetReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetReply) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lower         []byte                 `protobuf:"bytes,1,opt,name=lower,proto3" json:"lower,omitempty"`
	Upper         []byte                 `protobuf:"bytes,2,opt,name=upper,proto3" json:"upper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_tweets_tweets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tweets_tweets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_tweets_tweets_proto_rawDescGZIP(), []int{6}
}

func (x *ScanRequest) GetLower() []byte {
	if x != nil {
		return x.Lower
	}
	return nil
}

func (x *ScanRequest) GetUpper() []byte {
	if x != nil {
		return x.Upper
	}
	return nil
}

type KV struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KV) Reset() {
	*x = KV{}
	mi := &file_tweets_tweets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV) ProtoMessage() {}

func (x *KV) ProtoReflect() protoreflect.Message {
	mi := &file_tweets_tweets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV.ProtoReflect.Descriptor instead.
func (*KV) Descriptor() ([]byte, []int) {
	return file_tweets_tweets_proto_rawDescGZIP(), []int{7}
}

func (x *KV) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KV) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type LastReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Kv            *KV                    `protobuf:"bytes,2,opt,name=kv,proto3" json:"kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastReply) Reset() {
	*x = LastReply{}
	mi := &file_tweets_tweets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastReply) ProtoMessage() {}

func (x *LastReply) ProtoReflect() protoreflect.Message {
	mi := &file_tweets_tweets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastReply.ProtoReflect.Descriptor instead.
func (*LastReply) Descriptor() ([]byte, []int) {
	return file_tweets_tweets_proto_rawDescGZIP(), []int{8}
}

func (x *LastReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *LastReply) GetKv() *KV {
	if x != nil {
		return x.Kv
	}
	return nil
}

type PutBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kvs           []*KV                  `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBatchRequest) Reset() {
	*x = PutBatchRequest{}
	mi := &file_tweets_tweets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBatchRequest) ProtoMessage() {}

func (x *PutBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tweets_tweets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBatchRequest.ProtoReflect.Descriptor instead.
func (*PutBatchRequest) Descriptor() ([]byte, []int) {
	return file_tweets_tweets_proto_rawDescGZIP(), []int{9}
}

func (x *PutBatchRequest) GetKvs() []*KV {
	if x != nil {
		return x.Kvs
	}
	return nil
}

var File_tweets_tweets_proto protoreflect.FileDescriptor

const file_tweets_tweets_proto_rawDesc = "" +
	"\n" +
	"\x13tweets/tweets.proto\x12\x06tweets\"\x0e\n" +
	"\fFlushRequest\"\f\n" +
	"\n" +
	"FlushReply\"H\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x12\n" +
	"\x04sync\x18\x03 \x01(\bR\x04sync\"\n" +
	"\n" +
	"\bPutReply\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"6\n" +
	"\bGetReply\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"9\n" +
	"\vScanRequest\x12\x14\n" +
	"\x05lower\x18\x01 \x01(\fR\x05lower\x12\x14\n" +
	"\x05upper\x18\x02 \x01(\fR\x05upper\",\n" +
	"\x02KV\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"=\n" +
	"\tLastReply\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1a\n" +
	"\x02kv\x18\x02 \x01(\v2\n" +
	".tweets.KVR\x02kv\"/\n" +
	"\x0fPutBatchRequest\x12\x1c\n" +
	"\x03kvs\x18\x01 \x03(\v2\n" +
	".tweets.KVR\x03kvs2\xa7\x02\n" +
	"\x06Tweets\x121\n" +
	"\x05Flush\x12\x14.tweets.FlushRequest\x1a\x12.tweets.FlushReply\x12+\n" +
	"\x03Put\x12\x12.tweets.PutRequest\x1a\x10.tweets.PutReply\x12+\n" +
	"\x03Get\x12\x12.tweets.GetRequest\x1a\x10.tweets.GetReply\x12)\n" +
	"\x04Scan\x12\x13.tweets.ScanRequest\x1a\n" +
	".tweets.KV0\x01\x12.\n" +
	"\x04Last\x12\x13.tweets.ScanRequest\x1a\x11.tweets.LastReply\x125\n" +
	"\bPutBatch\x12\x17.tweets.PutBatchRequest\x1a\x10.tweets.PutReplyB\x16Z\x14twitter_clone/tweetsb\x06proto3"

var (
	file_tweets_tweets_proto_rawDescOnce sync.Once
	file_tweets_tweets_proto_rawDescData []byte
)

func file_tweets_tweets_proto_rawDescGZIP() []byte {
	file_tweets_tweets_proto_rawDescOnce.Do(func() {
		file_tweets_tweets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tweets_tweets_proto_rawDesc), len(file_tweets_tweets_proto_rawDesc)))
	})
	return file_tweets_tweets_proto_rawDescData
}

var file_tweets_tweets_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tweets_tweets_proto_goTypes = []any{
	(*FlushRequest)(nil),    // 0: tweets.FlushRequest
	(*FlushReply)(nil),      // 1: tweets.FlushReply
	(*PutRequest)(nil),      // 2: tweets.PutRequest
	(*PutReply)(nil),        // 3: tweets.PutReply
	(*GetRequest)(nil),      // 4: tweets.GetRequest
	(*GetReply)(nil),        // 5: tweets.GetReply
	(*ScanRequest)(nil),     // 6: tweets.ScanRequest
	(*KV)(nil),              // 7: tweets.KV
	(*LastReply)(nil),       // 8: tweets.LastReply
	(*PutBatchRequest)(nil), // 9: tweets.PutBatchRequest
}
var file_tweets_tweets_proto_depIdxs = []int32{
	7, // 0: tweets.LastReply.kv:type_name -> tweets.KV
	7, // 1: tweets.PutBatchRequest.kvs:type_name -> tweets.KV
	0, // 2: tweets.Tweets.Flush:input_type -> tweets.FlushRequest
	2, // 3: tweets.Tweets.Put:input_type -> tweets.PutRequest
	4, // 4: tweets.Tweets.Get:input_type -> tweets.GetRequest
	6, // 5: tweets.Tweets.Scan:input_type -> tweets.ScanRequest
	6, // 6: tweets.Tweets.Last:input_type -> tweets.ScanRequest
	9, // 7: tweets.Tweets.PutBatch:input_type -> tweets.PutBatchRequest
	1, // 8: tweets.Tweets.Flush:output_type -> tweets.FlushReply
	3, // 9: tweets.Tweets.Put:output_type -> tweets.PutReply
	5, // 10: tweets.Tweets.Get:output_type -> tweets.GetReply
	7, // 11: tweets.Tweets.Scan:output_type -> tweets.KV
	8, // 12: tweets.Tweets.Last:output_type -> tweets.LastReply
	3, // 13: tweets.Tweets.PutBatch:output_type -> tweets.PutReply
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tweets_tweets_proto_init() }
func file_tweets_tweets_proto_init() {
	if File_tweets_tweets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tweets_tweets_proto_rawDesc), len(file_tweets_tweets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tweets_tweets_proto_goTypes,
		DependencyIndexes: file_tweets_tweets_proto_depIdxs,
		MessageInfos:      file_tweets_tweets_proto_msgTypes,
	}.Build()
	File_tweets_tweets_proto = out.File
	file_tweets_tweets_proto_goTypes = nil
	file_tweets_tweets_proto_depIdxs = nil
}
