// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: tweets/tweets.proto

package tweets

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tweets_Flush_FullMethodName    = "/tweets.Tweets/Flush"
	Tweets_Put_FullMethodName      = "/tweets.Tweets/Put"
	Tweets_Get_FullMethodName      = "/tweets.Tweets/Get"
	Tweets_Scan_FullMethodName     = "/tweets.Tweets/Scan"
	Tweets_Last_FullMethodName     = "/tweets.Tweets/Last"
	Tweets_PutBatch_FullMethodName = "/tweets.Tweets/PutBatch"
)

// TweetsClient is the client API for Tweets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TweetsClient interface {
	Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushReply, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutReply, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KV], error)
	Last(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*LastReply, error)
	PutBatch(ctx context.Context, in *PutBatchRequest, opts ...grpc.CallOption) (*PutReply, error)
}

type tweetsClient struct {
	cc grpc.ClientConnInterface
}

func NewTweetsClient(cc grpc.ClientConnInterface) TweetsClient {
	return &tweetsClient{cc}
}

func (c *tweetsClient) Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushReply)
	err := c.cc.Invoke(ctx, Tweets_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tweetsClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutReply)
	err := c.cc.Invoke(ctx, Tweets_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tweetsClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReply)
	err := c.cc.Invoke(ctx, Tweets_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tweetsClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KV], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tweets_ServiceDesc.Streams[0], Tweets_Scan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanRequest, KV]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tweets_ScanClient = grpc.ServerStreamingClient[KV]

func (c *tweetsClient) Last(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*LastReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LastReply)
	err := c.cc.Invoke(ctx, Tweets_Last_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tweetsClient) PutBatch(ctx context.Context, in *PutBatchRequest, opts ...grpc.CallOption) (*PutReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutReply)
	err := c.cc.Invoke(ctx, Tweets_PutBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TweetsServer is the server API for Tweets service.
// All implementations must embed UnimplementedTweetsServer
// for forward compatibility.
type TweetsServer interface {
	Flush(context.Context, *FlushRequest) (*FlushReply, error)
	Put(context.Context, *PutRequest) (*PutReply, error)
	Get(context.Context, *GetRequest) (*GetReply, error)
	Scan(*ScanRequest, grpc.ServerStreamingServer[KV]) error
	Last(context.Context, *ScanRequest) (*LastReply, error)
	PutBatch(context.Context, *PutBatchRequest) (*PutReply, error)
	mustEmbedUnimplementedTweetsServer()
}

// UnimplementedTweetsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTweetsServer struct{}

func (UnimplementedTweetsServer) Flush(context.Context, *FlushRequest) (*FlushReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedTweetsServer) Put(context.Context, *PutRequest) (*PutReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedTweetsServer) Get(context.Context, *GetRequest) (*GetReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTweetsServer) Scan(*ScanRequest, grpc.ServerStreamingServer[KV]) error {
	return status.Error(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedTweetsServer) Last(context.Context, *ScanRequest) (*LastReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Last not implemented")
}
func (UnimplementedTweetsServer) PutBatch(context.Context, *PutBatchRequest) (*PutReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PutBatch not implemented")
}
func (UnimplementedTweetsServer) mustEmbedUnimplementedTweetsServer() {}
func (UnimplementedTweetsServer) testEmbeddedByValue()                {}

// UnsafeTweetsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TweetsServer will
// result in compilation errors.
type UnsafeTweetsServer interface {
	mustEmbedUnimplementedTweetsServer()
}

func RegisterTweetsServer(s grpc.ServiceRegistrar, srv TweetsServer) {
	// If the following call panics, it indicates UnimplementedTweetsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tweets_ServiceDesc, srv)
}

func _Tweets_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetsServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tweets_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetsServer).Flush(ctx, req.(*FlushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tweets_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetsServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tweets_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetsServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tweets_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tweets_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetsServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tweets_Scan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TweetsServer).Scan(m, &grpc.GenericServerStream[ScanRequest, KV]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tweets_ScanServer = grpc.ServerStreamingServer[KV]

func _Tweets_Last_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetsServer).Last(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tweets_Last_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetsServer).Last(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tweets_PutBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetsServer).PutBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tweets_PutBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetsServer).PutBatch(ctx, req.(*PutBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tweets_ServiceDesc is the grpc.ServiceDesc for Tweets service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tweets_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tweets.Tweets",
	HandlerType: (*TweetsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Flush",
			Handler:    _Tweets_Flush_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Tweets_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Tweets_Get_Handler,
		},
		{
			MethodName: "Last",
			Handler:    _Tweets_Last_Handler,
		},
		{
			MethodName: "PutBatch",
			Handler:    _Tweets_PutBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Scan",
			Handler:       _Tweets_Scan_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tweets/tweets.proto",
}
