syntax = "proto3";

package tweets;

option go_package = "twitter_clone/tweets";

service Tweets {
  rpc Flush(FlushRequest) returns (FlushReply);
  rpc Put(PutRequest) returns (PutReply);
  rpc Get(GetRequest) returns (GetReply);
  rpc Scan(ScanRequest) returns (stream KV);
  rpc Last(ScanRequest) returns (LastReply);
  rpc PutBatch(PutBatchRequest) returns (PutReply);
}

message FlushRequest {}
message FlushReply {}

message PutRequest {
  bytes key = 1;
  bytes value = 2;
  bool sync = 3;
}
message PutReply {}

message GetRequest {
  bytes key = 1;
}
message GetReply {
  bool found = 1;
  bytes value = 2;
}

message ScanRequest {
  bytes lower = 1;
  bytes upper = 2;
}

message KV {
  bytes key = 1;
  bytes value = 2;
}

message LastReply {
  bool found = 1;
  KV kv = 2;
}

message PutBatchRequest {
  repeated KV kvs = 1;
}